services:
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influx_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=medical
      - DOCKER_INFLUXDB_INIT_BUCKET=appointments
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token

  appointment-service:
    build: .
    ports:
      - "8001:8000"
    environment:
      - JWT_SECRET=your_jwt_secret_here
      - INFLUX_TOKEN=my-super-secret-token
      - INFLUX_URL=http://influxdb:8086
    depends_on:
      - influxdb

volumes:
  influx_data: