version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"         
      - "15672:15672"        
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  doctor-db:
    image: postgres:15
    environment:
      POSTGRES_DB: doctordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - doctor-db-data:/var/lib/postgresql/data

  doctor-service:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_PORT: 5432
      DB_HOST: doctor-db
      DB_NAME: doctordb
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: your_jwt_secret_here
      AMQP_URL: amqp://admin:admin@rabbitmq
    depends_on:
      - doctor-db
      - rabbitmq

volumes:
  doctor-db-data: