name: Build and Push to ECR

on:
  workflow_run:
    workflows: ["Test Workflow"]
    types:
      - completed

env:
  AWS_REGION: us-east-1
  ECR_BASE: 730335435249.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push images
        run: |
          SERVICES=(
            "doctor-service"
            "patient-service"
            "medical-file-upload-service"
            "appointment-service"
          )

          for SERVICE in "${SERVICES[@]}"; do
            echo "Building $SERVICE..."
            docker build -t $ECR_BASE/$SERVICE:${{ github.sha }} ./$SERVICE
            docker push $ECR_BASE/$SERVICE:${{ github.sha }}
            echo "Successfully pushed $ECR_BASE/$SERVICE:${{ github.sha }}"
          done